global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
          - 'host.docker.internal:8081'
  - job_name: 'temporalmetrics java'
    metrics_path: /metrics
    scheme: http
    static_configs:
      # Server metrics target
      #- targets:
      #    - 'host.docker.internal:8000'
      #    - 'host.docker.internal:8001'
      #    - 'host.docker.internal:8002'
      #    - 'host.docker.internal:8003'
      #  labels:
      #    group: 'server-metrics'

      # Local app targets (if configured)
      - targets:
          - 'host.docker.internal:8071'
          - 'host.docker.internal:8072'
          - 'host.docker.internal:8073'
          - 'host.docker.internal:8074'
          - 'host.docker.internal:8075'
          - 'host.docker.internal:8076'
          - 'host.docker.internal:8077'
          - 'host.docker.internal:8078'
          - 'host.docker.internal:8079'
        labels:
          group: 'sdk-metrics'
      # Docker metrics
     # - targets:
     #     - 'host.docker.internal:9323'
     #   labels:
     #     group: 'docker-metrics'
      # Postgres Exporter
     # - targets:
     #     - 'host.docker.internal:9187'
     #   labels:
     #     group: 'postgres-metrics'
  - job_name: 'temporalmetrics typescript'
    metrics_path: /metrics
    scheme: http
    static_configs:
      # Server metrics target
      #- targets:
      #    - 'host.docker.internal:8000'
      #    - 'host.docker.internal:8001'
      #    - 'host.docker.internal:8002'
      #    - 'host.docker.internal:8003'
      #  labels:
      #    group: 'server-metrics'

      # Local app targets (if configured)
      - targets:
          - 'host.docker.internal:9464'
        labels:
          group: 'sdk-metrics'
      # Docker metrics
     # - targets:
     #     - 'host.docker.internal:9323'
     #   labels:
     #     group: 'docker-metrics'
      # Postgres Exporter
     # - targets:
     #     - 'host.docker.internal:9187'
     #   labels:
     #     group: 'postgres-metrics'
  - job_name: 'temporalmetrics go'
    metrics_path: /metrics
    scheme: http
    static_configs:
      # Server metrics target
      #- targets:
      #    - 'host.docker.internal:8000'
      #    - 'host.docker.internal:8001'
      #    - 'host.docker.internal:8002'
      #    - 'host.docker.internal:8003'
      #  labels:
      #    group: 'server-metrics'

      # Local app targets (if configured)
      - targets:
          - 'host.docker.internal:9091'
        labels:
          group: 'sdk-metrics'
      # Docker metrics
     # - targets:
     #     - 'host.docker.internal:9323'
     #   labels:
     #     group: 'docker-metrics'
      # Postgres Exporter
     # - targets:
     #     - 'host.docker.internal:9187'
     #   labels:
     #     group: 'postgres-metrics'




